# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aoede Linux Development News
email: admin@aoede
description: >- # this means to ignore newlines until "baseurl:"
        An Indignados Media production:
                Aoede Linux, an Arch Linux-based audio distribution

        Aoede aims to satisfy the needs of serious audio producers with a no-frills approach to UI based on Arch-way minimalism and FLOSS audio software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://atrusofthefuture.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: @indignadosmedia
github_username: atrusofthefuture

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
